// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZl-eDKhFIu1H0jQuMz77zFdZvrvKC_4Y',
    appId: '1:15207012068:web:f0440f2825e7494c09fef1',
    messagingSenderId: '15207012068',
    projectId: 'capstoneflutter-97637',
    authDomain: 'capstoneflutter-97637.firebaseapp.com',
    storageBucket: 'capstoneflutter-97637.appspot.com',
    measurementId: 'G-HXCL60P2TQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgDEsLlgJBC4QycM4RiytSYRnpz3NFP_A',
    appId: '1:15207012068:android:ae34428512cff73e09fef1',
    messagingSenderId: '15207012068',
    projectId: 'capstoneflutter-97637',
    storageBucket: 'capstoneflutter-97637.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU58u-NC1l45cRk6VoeCrncS2bBZIQ81M',
    appId: '1:15207012068:ios:63379cc006fa523309fef1',
    messagingSenderId: '15207012068',
    projectId: 'capstoneflutter-97637',
    storageBucket: 'capstoneflutter-97637.appspot.com',
    iosClientId: '15207012068-0tne6b6p67oh33ae9th4ef9btp0jglpk.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstoneFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU58u-NC1l45cRk6VoeCrncS2bBZIQ81M',
    appId: '1:15207012068:ios:63379cc006fa523309fef1',
    messagingSenderId: '15207012068',
    projectId: 'capstoneflutter-97637',
    storageBucket: 'capstoneflutter-97637.appspot.com',
    iosClientId: '15207012068-0tne6b6p67oh33ae9th4ef9btp0jglpk.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstoneFlutter',
  );
}
